### ISSUE TITLE
Can't login to RWL

### ISSUE THREAD

**Issue by blairconrad** [LibraryHippo/LibraryHippo#33]
```
Traceback (most recent call last):
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/cardchecker.py", line 39, in check card_status = library_account.get_status()
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/rwl.py", line 135, in get_status my_account_url = self.login()
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/rwl.py", line 61, in login login_response = self.fetcher(submit_login_url, form_fields)
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/gael/urlfetch.py", line 119, in __call__ response = self.fetcher(url, payload, method, headers, allow_truncated, follow_redirects, deadline)
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/gael/urlfetch.py", line 99, in __call__ return self.fetcher(url, payload, method, headers, allow_truncated, follow_redirects, deadline)
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/gael/urlfetch.py", line 72, in __call__ allow_truncated, False, deadline)
File "/base/data/home/apps/s~libraryhippo27/1.387800117317232253/gael/urlfetch.py", line 50, in __call__ allow_truncated, follow_redirects, deadline)
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 271, in fetch return rpc.get_result()
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result return self.__get_result_hook(self)
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 389, in _get_fetch_result 'Invalid request URL: ' + url + error_detail) InvalidURLError: Invalid request URL: /client/en_US/rwl/search/patronlogin.loginpageform/WATERLOO?&t:ac=http:$002f$002folco.ent.sirsidynix.net$002fclient$002fen_US$002frwl$002fsearch$002faccount$003f
```

**Comment by blairconrad** [comment]
Fixed by #34.
